### ISSUE TITLE
Upgrade to Commanded and EventStore v1.0 

### ISSUE THREAD

**Issue by Ciboulette** [slashdotdash/segment-challenge#1]
Hey @slashdotdash,

Massive fan of your work on Commanded and your example repositories! 😎

I was wondering if you are planning to upgrade this one to Commanded & EventStore v1.*? 

Keep going! 💪

**Comment by slashdotdash** [comment]
Thanks for the kind words.

No, I don't have any immediate plans to update Segment Challenge. If you want to see what's involved with upgrading an existing app using Commanded to v1.0.0 then take a look at the [pull request to apply the upgrade to the Conduit example repo](https://github.com/slashdotdash/conduit/pull/25).
